export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const ERROR_GET_ALL_COUNTRIES = "ERROR_GET_ALL_COUNTRIES";
export const GET_CODE_COUNTRY = "GET_CODE_COUNTRY";
export const DELETE_CODE_COUNTRY = "DELETE_CODE_COUNTRY";
export const ERROR_GET_COUNTRY = "ERROR_GET_COUNTRY";
export const GET_COUNTRIES_TO_SHOW = "GET_COUNTRIES_TO_SHOW";
export const DELETE_COUNTRIES_TO_SHOW = "DELETE_COUNTRIES_TO_SHOW";
export const DELETE_COUNTRIES_BY_REGION = "DELETE_COUNTRIES_BY_REGION";

export const GET_TAG = "GET_TAG";
export const GET_REGION = "GET_REGION";
export const HANDLE_PILLS = "HANDLE_PILLS";
export const RESET_VALUES = "RESET_VALUES";
export const ACTIVE_DARK_MODE = "ACTIVE_DARK_MODE";
export const SHOW_MODAL = "SHOW_MODAL";
export const ADD_COUNTRIES_BY_REGION = "ADD_COUNTRIES_BY_REGION";
