export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_CODE_COUNTRY = "GET_CODE_COUNTRY";
export const DELETE_CODE_COUNTRY = "DELETE_CODE_COUNTRY";
export const ERROR_GET_ALL_COUNTRIES = "ERROR_GET_ALL_COUNTRIES";
export const ACTIVE_DARK_MODE = "ACTIVE_DARK_MODE";
